# setup-template.ps1
#
# Base template for canary Full mode sandbox evaluation.
# Canary fills in the placeholders below and writes the result to C:\sandbox\scripts\setup.ps1
# before each Full mode scan. Do not edit this file directly — edit the template in the repo.
#
# Placeholders (canary replaces these at scan time):
#   {{TARGET_NAME}}   — friendly name for logging (e.g. "shadPS4")
#   {{TARGET_URL}}    — direct download URL for the release binary or archive
#   {{BINARY_NAME}}   — exact filename of the executable (e.g. "shadPS4.exe")
#   {{EXTRACT_DIR}}   — directory to extract/place the binary (e.g. "C:\shadps4_local")
#   {{LAUNCH_ARGS}}   — command line arguments for the binary (leave empty if none)

$LogFile  = 'C:\sandbox\output\setup.log'
$Sentinel = 'C:\sandbox\output\done.sentinel'

# Start transcript immediately so watchdog sees setup.log
Start-Transcript -Path $LogFile -Append -Force

# ── 1. SAC state (logged first — critical for diagnosing blocked binaries) ──────

$sacState = (Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\CI\Policy' -ErrorAction SilentlyContinue).VerifiedAndReputablePolicyState
Write-Host "SAC state: $sacState (0=Off, 1=Evaluation, 2=On, null=Not present)"

# ── 2. Internal Procmon (timestamped — avoids overwrite prompts on retry) ────────

$ts = Get-Date -Format 'yyyyMMdd-HHmmss'
$procmon = 'C:\tools\Sysinternals\Procmon64.exe'
if (Test-Path $procmon) {
    Start-Process $procmon -ArgumentList "/accepteula /quiet /minimized /backingfile C:\sandbox\output\procmon-internal-$ts.pml"
    Write-Host "Procmon started -> procmon-internal-$ts.pml"
} else {
    Write-Host "WARNING: Procmon not found at $procmon — internal process capture skipped."
}

# ── 3. Target variables (filled in by canary) ─────────────────────────────────

$targetName = '{{TARGET_NAME}}'
$targetUrl  = '{{TARGET_URL}}'
$binaryName = '{{BINARY_NAME}}'
$extractDir = '{{EXTRACT_DIR}}'
$launchArgs = '{{LAUNCH_ARGS}}'

Write-Host "Target: $targetName"
Write-Host "URL:    $targetUrl"
Write-Host "Binary: $binaryName"

# ── 4. Install VC++ redistributable (most Windows binaries require it) ───────────

Write-Host "Installing VC++ 2022 redistributable..."
$vcUrl  = 'https://aka.ms/vs/17/release/vc_redist.x64.exe'
$vcDest = 'C:\vcredist.exe'
try {
    Invoke-WebRequest -Uri $vcUrl -OutFile $vcDest -UseBasicParsing
    $vcResult = Start-Process $vcDest -ArgumentList '/quiet /norestart' -Wait -PassThru
    Write-Host "VC++ install exit code: $($vcResult.ExitCode)"
} catch {
    Write-Host "WARNING: VC++ install failed: $($_.Exception.Message) — continuing anyway."
}

# ── 5. Download target binary ─────────────────────────────────────────────────

Write-Host "Downloading $targetName ..."
New-Item -ItemType Directory -Force -Path $extractDir | Out-Null

# Determine if URL points to a zip or direct executable
$isZip = $targetUrl -match '\.zip($|\?)'
$downloadDest = if ($isZip) { "$extractDir\download.zip" } else { "$extractDir\$binaryName" }

try {
    Invoke-WebRequest -Uri $targetUrl -OutFile $downloadDest -UseBasicParsing
    Write-Host "Download complete: $downloadDest ($([math]::Round((Get-Item $downloadDest).Length/1MB,1)) MB)"
} catch {
    Write-Host "RESULT: Binary could not be launched. Download failed: $($_.Exception.GetType().Name): $($_.Exception.Message)"
    Stop-Transcript
    "done" | Out-File $Sentinel -Encoding UTF8 -Force
    exit 1
}

# ── 6. Extract if zip ─────────────────────────────────────────────────────────

if ($isZip) {
    Write-Host "Extracting to $extractDir ..."
    try {
        Expand-Archive -Path $downloadDest -DestinationPath $extractDir -Force
        Write-Host "Extracted files:"
        Get-ChildItem $extractDir -Recurse -File | Select-Object -ExpandProperty FullName | ForEach-Object { Write-Host "  $_" }
    } catch {
        Write-Host "RESULT: Binary could not be launched. Extraction failed: $($_.Exception.GetType().Name): $($_.Exception.Message)"
        Stop-Transcript
        "done" | Out-File $Sentinel -Encoding UTF8 -Force
        exit 1
    }
}

# ── 7. Locate the binary (case-insensitive, fallback to any .exe) ─────────────

$exePath = Get-ChildItem $extractDir -Recurse -File |
    Where-Object { $_.Name -ieq $binaryName } |
    Select-Object -First 1 -ExpandProperty FullName

if (-not $exePath) {
    Write-Host "WARNING: $binaryName not found by exact name. Searching for any .exe..."
    $exePath = Get-ChildItem $extractDir -Recurse -File -Filter '*.exe' |
        Select-Object -First 1 -ExpandProperty FullName
}

if (-not $exePath) {
    Write-Host "RESULT: Binary could not be launched. No executable found in $extractDir."
    Stop-Transcript
    "done" | Out-File $Sentinel -Encoding UTF8 -Force
    exit 1
}

Write-Host "Binary located: $exePath"

# ── 8. Launch the binary ──────────────────────────────────────────────────────

Write-Host "Launching: $exePath $launchArgs"
try {
    $proc = if ($launchArgs) {
        Start-Process -FilePath $exePath -ArgumentList $launchArgs -PassThru -ErrorAction Stop
    } else {
        Start-Process -FilePath $exePath -PassThru -ErrorAction Stop
    }
    Write-Host "Process started: PID $($proc.Id)"
} catch {
    $errMsg = $_.Exception.Message
    if ($errMsg -match 'Application Control|WDAC|policy has blocked|WinError 4551') {
        Write-Host "RESULT: Binary blocked -- WDAC/Application Control policy"
        Write-Host "The sandbox has its own Application Control enforcement independent of host SAC."
        Write-Host "Error: $($_.Exception.GetType().Name): $errMsg"
    } else {
        Write-Host "RESULT: Binary could not be launched. Possible causes: missing dependency, corrupt binary."
        Write-Host "Error: $($_.Exception.GetType().Name): $errMsg"
    }
    Stop-Transcript
    "done" | Out-File $Sentinel -Encoding UTF8 -Force
    exit 1
}

# ── 9. Confirm process is running ─────────────────────────────────────────────

Start-Sleep -Seconds 5
$baseName = [System.IO.Path]::GetFileNameWithoutExtension($binaryName)
$running = Get-Process | Where-Object {
    $_.Path -ieq $exePath -or $_.Name -ieq $baseName
} | Select-Object -First 1

if ($running) {
    Write-Host "RESULT: Binary launched successfully. PID $($running.Id) is running."
} else {
    Write-Host "RESULT: Binary could not be launched. Process not found after launch attempt."
    Write-Host "Possible causes: SAC/WDAC policy, missing dependency, corrupt binary, or process exited immediately."
    Stop-Transcript
    "done" | Out-File $Sentinel -Encoding UTF8 -Force
    exit 1
}

# ── 10. Observation period (watchdog streams output in real time) ─────────────

Write-Host "Observing for 120 seconds — monitoring network, process, and file activity..."
Start-Sleep -Seconds 120
Write-Host "Observation complete."

# ── 11. Teardown ──────────────────────────────────────────────────────────────

Write-Host "Stopping target process..."
$running | Stop-Process -Force -ErrorAction SilentlyContinue
Write-Host "Done."

Stop-Transcript
"done" | Out-File $Sentinel -Encoding UTF8 -Force
